services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    develop:
      watch:
        - action: sync
          path: ./apps/reservations
          target: /usr/src/app/apps/reservations/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/reservations/src

  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    develop:
      watch:
        - action: sync
          path: ./apps/auth
          target: /usr/src/app/apps/auth/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/auth/src
  payments: 
    build: 
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    env_file:
      - ./apps/payments/.env
    develop:
      watch:
        - action: sync
          path: ./apps/payments
          target: /usr/src/app/apps/payments/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/payments/src
